export const TODOS_LIST_FAILURE = 'TODOS/LIST/FAILURE';
export const TODOS_LIST_REQUEST = 'TODOS/LIST/REQUEST';
export const TODOS_LIST_SUCCESS = 'TODOS/LIST/SUCCESS';

export const TODO_ADD_FAILURE = 'TODO/ADD/FAILURE';
export const TODO_ADD_REQUEST = 'TODO/ADD/REQUEST';
export const TODO_ADD_SUCCESS = 'TODO/ADD/SUCCESS';

export const TODO_DELETE_FAILURE = 'TODO/DELETE/FAILURE';
export const TODO_DELETE_REQUEST = 'TODO/DELETE/REQUEST';
export const TODO_DELETE_SUCCESS = 'TODO/DELETE/SUCCESS';

export const TODO_EDIT_FAILURE = 'TODO/EDIT/FAILURE';
export const TODO_EDIT_REQUEST = 'TODO/EDIT/REQUEST';
export const TODO_EDIT_SUCCESS = 'TODO/EDIT/SUCCESS';
